services:
  - type: web
    name: fakeapi
    env: python
    plan: free
    region: oregon
    buildCommand: "pip install poetry && poetry install"
    startCommand: "poetry run uvicorn fakeapi.main:app --host 0.0.0.0 --port $PORT --reload"
    envVars:
      - key: PORT
        value: 8000
